-- ============================================================================
-- V1: Core tenancy + authentication
-- Portable DDL that runs on PostgreSQL 16 and on H2 (MODE=PostgreSQL).
-- Money is stored as integer minor units (kobo) in BIGINT columns.
-- ============================================================================

CREATE TABLE schools (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(200) NOT NULL,
    code               VARCHAR(60)  NOT NULL,
    email              VARCHAR(200),
    phone              VARCHAR(30),
    address            VARCHAR(500),
    logo_url           VARCHAR(500),
    currency           VARCHAR(3)   NOT NULL DEFAULT 'NGN',
    has_day            BOOLEAN      NOT NULL DEFAULT TRUE,
    has_boarding       BOOLEAN      NOT NULL DEFAULT FALSE,
    nomba_account_id   VARCHAR(100),
    nomba_account_ref  VARCHAR(100),
    status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT       NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_schools_code ON schools (code);

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id      BIGINT,
    email          VARCHAR(200) NOT NULL,
    phone          VARCHAR(30),
    password_hash  VARCHAR(200) NOT NULL,
    first_name     VARCHAR(100),
    last_name      VARCHAR(100),
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at  TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_users_school FOREIGN KEY (school_id) REFERENCES schools (id)
);
CREATE UNIQUE INDEX ux_users_email ON users (email);
CREATE INDEX ix_users_school ON users (school_id);

CREATE TABLE roles (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX ux_roles_name ON roles (name);

CREATE TABLE user_roles (
    user_id  BIGINT NOT NULL,
    role_id  BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

INSERT INTO roles (name) VALUES
    ('PLATFORM_ADMIN'),
    ('SCHOOL_ADMIN'),
    ('BURSAR'),
    ('PARENT'),
    ('GUARDIAN');
