-- ============================================================================
-- V2: Academic structure + fees
-- ============================================================================

CREATE TABLE sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT      NOT NULL,
    name        VARCHAR(50) NOT NULL,
    start_date  DATE,
    end_date    DATE,
    is_current  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    version     BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_sessions_school FOREIGN KEY (school_id) REFERENCES schools (id)
);
CREATE UNIQUE INDEX ux_sessions_school_name ON sessions (school_id, name);

CREATE TABLE terms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT      NOT NULL,
    session_id  BIGINT      NOT NULL,
    name        VARCHAR(20) NOT NULL,
    sequence    INT         NOT NULL,
    start_date  DATE,
    end_date    DATE,
    is_current  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    version     BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_terms_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_terms_session FOREIGN KEY (session_id) REFERENCES sessions (id)
);
CREATE UNIQUE INDEX ux_terms_session_sequence ON terms (session_id, sequence);

CREATE TABLE classes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    BIGINT      NOT NULL,
    name         VARCHAR(50) NOT NULL,
    level_order  INT         NOT NULL DEFAULT 0,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    version      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_classes_school FOREIGN KEY (school_id) REFERENCES schools (id)
);
CREATE UNIQUE INDEX ux_classes_school_name ON classes (school_id, name);

CREATE TABLE fee_structures (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       BIGINT      NOT NULL,
    class_id        BIGINT      NOT NULL,
    session_id      BIGINT      NOT NULL,
    term_id         BIGINT      NOT NULL,
    residency_type  VARCHAR(10) NOT NULL,
    amount_kobo     BIGINT      NOT NULL,
    description     VARCHAR(200),
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_fees_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_fees_class FOREIGN KEY (class_id) REFERENCES classes (id),
    CONSTRAINT fk_fees_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_fees_term FOREIGN KEY (term_id) REFERENCES terms (id)
);
CREATE UNIQUE INDEX ux_fees_class_term_residency ON fee_structures (class_id, term_id, residency_type);

-- Immutable history of every fee amount change (who/when/old/new/reason).
CREATE TABLE fee_change_log (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT      NOT NULL,
    fee_structure_id   BIGINT,
    class_id           BIGINT      NOT NULL,
    session_id         BIGINT      NOT NULL,
    term_id            BIGINT      NOT NULL,
    residency_type     VARCHAR(10) NOT NULL,
    old_amount_kobo    BIGINT,
    new_amount_kobo    BIGINT      NOT NULL,
    reason             VARCHAR(300),
    changed_by_user_id BIGINT,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_feelog_school FOREIGN KEY (school_id) REFERENCES schools (id)
);
CREATE INDEX ix_feelog_school ON fee_change_log (school_id);
CREATE INDEX ix_feelog_class_term ON fee_change_log (class_id, term_id);
