-- ============================================================================
-- V3: People (students, guardians, mappings, enrollments)
-- ============================================================================

CREATE TABLE students (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       BIGINT       NOT NULL,
    admission_no    VARCHAR(50)  NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    middle_name     VARCHAR(100),
    gender          VARCHAR(10),
    date_of_birth   DATE,
    class_id        BIGINT,
    residency_type  VARCHAR(10)  NOT NULL DEFAULT 'DAY',
    photo_url       VARCHAR(500),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_students_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_students_class FOREIGN KEY (class_id) REFERENCES classes (id)
);
CREATE UNIQUE INDEX ux_students_school_admission ON students (school_id, admission_no);
CREATE INDEX ix_students_school_class ON students (school_id, class_id);
CREATE INDEX ix_students_names ON students (school_id, last_name, first_name);

CREATE TABLE guardians (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT       NOT NULL,
    user_id     BIGINT,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(200),
    phone       VARCHAR(30)  NOT NULL,
    address     VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_guardians_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_guardians_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_guardians_school_phone ON guardians (school_id, phone);
CREATE INDEX ix_guardians_school_email ON guardians (school_id, email);

CREATE TABLE student_guardians (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           BIGINT      NOT NULL,
    student_id          BIGINT      NOT NULL,
    guardian_id         BIGINT      NOT NULL,
    relationship        VARCHAR(30) NOT NULL DEFAULT 'GUARDIAN',
    is_primary          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_payer            BOOLEAN     NOT NULL DEFAULT TRUE,
    is_delegated_payer  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,
    version             BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_sg_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_sg_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_sg_guardian FOREIGN KEY (guardian_id) REFERENCES guardians (id)
);
CREATE UNIQUE INDEX ux_sg_student_guardian ON student_guardians (student_id, guardian_id);
CREATE INDEX ix_sg_guardian ON student_guardians (guardian_id);

CREATE TABLE enrollments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       BIGINT      NOT NULL,
    student_id      BIGINT      NOT NULL,
    session_id      BIGINT      NOT NULL,
    class_id        BIGINT      NOT NULL,
    residency_type  VARCHAR(10) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_enr_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_enr_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_enr_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_enr_class FOREIGN KEY (class_id) REFERENCES classes (id)
);
CREATE UNIQUE INDEX ux_enr_student_session ON enrollments (student_id, session_id);
CREATE INDEX ix_enr_session_class ON enrollments (school_id, session_id, class_id);
