-- ============================================================================
-- V4: Scholarships + billing (invoices, ledger, credit wallet)
-- The append-only ledger is the audit source of truth; invoices and the credit
-- wallet are materialised for fast reads and reconciled against the ledger.
-- ============================================================================

CREATE TABLE scholarships (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    BIGINT       NOT NULL,
    name         VARCHAR(150) NOT NULL,
    type         VARCHAR(20)  NOT NULL,          -- PERCENTAGE | FIXED
    percentage   NUMERIC(5,2),                   -- when type = PERCENTAGE
    amount_kobo  BIGINT,                          -- when type = FIXED
    sponsor      VARCHAR(150),
    description  VARCHAR(300),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_scholarship_school FOREIGN KEY (school_id) REFERENCES schools (id)
);
CREATE INDEX ix_scholarships_school ON scholarships (school_id);

-- An award of a scholarship to a student (snapshotted so template edits don't rewrite history).
CREATE TABLE student_scholarships (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         BIGINT      NOT NULL,
    student_id        BIGINT      NOT NULL,
    scholarship_id    BIGINT,
    session_id        BIGINT,                     -- null = all sessions
    term_id           BIGINT,                     -- null = all terms in the session
    type              VARCHAR(20) NOT NULL,
    percentage        NUMERIC(5,2),
    amount_kobo       BIGINT,
    status            VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    awarded_by_user_id BIGINT,
    note              VARCHAR(300),
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP,
    version           BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_ss_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_ss_student FOREIGN KEY (student_id) REFERENCES students (id)
);
CREATE INDEX ix_ss_student ON student_scholarships (student_id);

CREATE TABLE invoices (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id               BIGINT      NOT NULL,
    student_id              BIGINT      NOT NULL,
    session_id              BIGINT      NOT NULL,
    term_id                 BIGINT      NOT NULL,
    class_id                BIGINT      NOT NULL,
    residency_type          VARCHAR(10) NOT NULL,
    gross_amount_kobo       BIGINT      NOT NULL,
    scholarship_amount_kobo BIGINT      NOT NULL DEFAULT 0,
    credit_applied_kobo     BIGINT      NOT NULL DEFAULT 0,
    net_amount_kobo         BIGINT      NOT NULL,
    amount_paid_kobo        BIGINT      NOT NULL DEFAULT 0,
    balance_kobo            BIGINT      NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP,
    version                 BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_inv_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_inv_student FOREIGN KEY (student_id) REFERENCES students (id)
);
CREATE UNIQUE INDEX ux_invoices_student_term ON invoices (student_id, term_id);
CREATE INDEX ix_invoices_school_status ON invoices (school_id, status);
CREATE INDEX ix_invoices_school_session_term ON invoices (school_id, session_id, term_id);

-- Append-only. amount_kobo is SIGNED: positive = charge (increases balance owed),
-- negative = credit (payment / scholarship / carried-in credit).
CREATE TABLE ledger_entries (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT      NOT NULL,
    student_id         BIGINT      NOT NULL,
    session_id         BIGINT,
    term_id            BIGINT,
    invoice_id         BIGINT,
    entry_type         VARCHAR(30) NOT NULL,
    amount_kobo        BIGINT      NOT NULL,
    reference          VARCHAR(120),
    description        VARCHAR(300),
    created_by_user_id BIGINT,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_ledger_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_ledger_student FOREIGN KEY (student_id) REFERENCES students (id)
);
CREATE INDEX ix_ledger_student ON ledger_entries (student_id);
CREATE INDEX ix_ledger_school ON ledger_entries (school_id);
CREATE INDEX ix_ledger_invoice ON ledger_entries (invoice_id);

-- Running credit wallet per student (overpayment carried to the next term).
CREATE TABLE student_credits (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    BIGINT    NOT NULL,
    student_id   BIGINT    NOT NULL,
    balance_kobo BIGINT    NOT NULL DEFAULT 0,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    version      BIGINT    NOT NULL DEFAULT 0,
    CONSTRAINT fk_credit_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_credit_student FOREIGN KEY (student_id) REFERENCES students (id)
);
CREATE UNIQUE INDEX ux_student_credits_student ON student_credits (student_id);
