-- ============================================================================
-- V5: Payments (orders, allocations, Nomba virtual accounts, transactions, offline)
-- ============================================================================

CREATE TABLE payment_orders (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT      NOT NULL,
    reference          VARCHAR(60) NOT NULL,
    payer_guardian_id  BIGINT,
    channel            VARCHAR(20) NOT NULL,
    total_amount_kobo  BIGINT      NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'AWAITING_PAYMENT',
    note               VARCHAR(300),
    created_by_user_id BIGINT,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_order_school FOREIGN KEY (school_id) REFERENCES schools (id)
);
CREATE UNIQUE INDEX ux_orders_reference ON payment_orders (reference);
CREATE INDEX ix_orders_school ON payment_orders (school_id);

CREATE TABLE payment_allocations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    BIGINT  NOT NULL,
    order_id     BIGINT  NOT NULL,
    student_id   BIGINT  NOT NULL,
    invoice_id   BIGINT,
    amount_kobo  BIGINT  NOT NULL,
    applied      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    version      BIGINT  NOT NULL DEFAULT 0,
    CONSTRAINT fk_alloc_order FOREIGN KEY (order_id) REFERENCES payment_orders (id),
    CONSTRAINT fk_alloc_student FOREIGN KEY (student_id) REFERENCES students (id)
);
CREATE INDEX ix_alloc_order ON payment_allocations (order_id);

CREATE TABLE virtual_accounts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id            BIGINT      NOT NULL,
    order_id             BIGINT      NOT NULL,
    account_ref          VARCHAR(80) NOT NULL,
    account_number       VARCHAR(20),
    account_name         VARCHAR(120),
    bank_name            VARCHAR(120),
    expected_amount_kobo BIGINT      NOT NULL,
    expiry_at            TIMESTAMP,
    provider             VARCHAR(20) NOT NULL DEFAULT 'NOMBA',
    status               VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP,
    version              BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_va_order FOREIGN KEY (order_id) REFERENCES payment_orders (id)
);
CREATE UNIQUE INDEX ux_va_account_ref ON virtual_accounts (account_ref);
CREATE INDEX ix_va_school ON virtual_accounts (school_id);

CREATE TABLE payment_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT,
    order_id           BIGINT,
    provider           VARCHAR(20)  NOT NULL DEFAULT 'NOMBA',
    provider_reference VARCHAR(120) NOT NULL,
    account_ref        VARCHAR(80),
    amount_kobo        BIGINT       NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    matched            BOOLEAN      NOT NULL DEFAULT FALSE,
    paid_at            TIMESTAMP,
    raw_payload        VARCHAR,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT       NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_txn_provider_reference ON payment_transactions (provider, provider_reference);
CREATE INDEX ix_txn_school ON payment_transactions (school_id);
CREATE INDEX ix_txn_account_ref ON payment_transactions (account_ref);

CREATE TABLE offline_payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT      NOT NULL,
    student_id         BIGINT      NOT NULL,
    invoice_id         BIGINT,
    method             VARCHAR(20) NOT NULL,
    amount_kobo        BIGINT      NOT NULL,
    reference          VARCHAR(120),
    note               VARCHAR(300),
    recorded_by_user_id BIGINT,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_offline_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_offline_student FOREIGN KEY (student_id) REFERENCES students (id)
);
CREATE INDEX ix_offline_school ON offline_payments (school_id);
CREATE INDEX ix_offline_student ON offline_payments (student_id);
