-- ============================================================================
-- V6: Reconciliation, notifications and audit (cross-cutting)
-- ============================================================================

CREATE TABLE reconciliation_runs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_count    INT       NOT NULL DEFAULT 0,
    exception_count  INT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    version          BIGINT    NOT NULL DEFAULT 0
);

CREATE TABLE reconciliation_exceptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           BIGINT,
    type                VARCHAR(30) NOT NULL,     -- UNMATCHED_CREDIT | AMOUNT_MISMATCH | LEDGER_IMBALANCE
    transaction_id      BIGINT,
    reference           VARCHAR(120),
    expected_amount_kobo BIGINT,
    actual_amount_kobo  BIGINT,
    detail              VARCHAR(300),
    resolved            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,
    version             BIGINT      NOT NULL DEFAULT 0
);
CREATE INDEX ix_recon_exc_school ON reconciliation_exceptions (school_id);
CREATE INDEX ix_recon_exc_txn ON reconciliation_exceptions (transaction_id);

CREATE TABLE notification_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     BIGINT,
    channel       VARCHAR(10) NOT NULL,           -- EMAIL | SMS
    recipient     VARCHAR(200) NOT NULL,
    subject       VARCHAR(200),
    body          VARCHAR,
    status        VARCHAR(20) NOT NULL,           -- SENT | FAILED
    provider_ref  VARCHAR(120),
    error         VARCHAR(300),
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    version       BIGINT      NOT NULL DEFAULT 0
);
CREATE INDEX ix_notif_school ON notification_logs (school_id);

CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     BIGINT,
    actor_user_id BIGINT,
    action        VARCHAR(80)  NOT NULL,
    entity_type   VARCHAR(60),
    entity_id     VARCHAR(60),
    before_json   VARCHAR,
    after_json    VARCHAR,
    ip_address    VARCHAR(60),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    version       BIGINT       NOT NULL DEFAULT 0
);
CREATE INDEX ix_audit_school ON audit_logs (school_id);
CREATE INDEX ix_audit_entity ON audit_logs (entity_type, entity_id);
